name: Task 1 - Run echo hello Aravindan the world is yours

on:
  push:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello world
        run: echo 'hello Aravindan the world is yours'
