name: Task 1 - Run echo hello Aravindan the world is yours

on:
  push:
    branches:
      - main
  pull-request:
    branches:
      - main

jobs:
  hello-world-new:
    runs-on: ubuntu-latest
    steps:
      - name: Run hello world from github
        run: echo 'hello Aravindan the world is yours'
